/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webroom.gui;

/**
 *
 * @author patri
 */
public class RendererStatus extends javax.swing.JPanel {

    /**
     * Creates new form panRendererStatus
     */
    public RendererStatus() {
        initComponents();
    }

    public void resetStatus(){
       txtMessages.setText("");
    }
    public void updateStatus(String msg){
        txtMessages.append(msg + "\n");
        txtMessages.setCaretPosition(txtMessages.getText().length()-1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        txtMessages.setBackground(new java.awt.Color(0, 0, 0));
        txtMessages.setColumns(20);
        txtMessages.setForeground(new java.awt.Color(0, 255, 0));
        txtMessages.setRows(5);
        jScrollPane2.setViewportView(txtMessages);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables
}
