/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webroom.gui;

import java.awt.Rectangle;
import java.net.URL;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import webroom.engine.Message;

/**
 *
 * @author patri
 */
public class VideoPanel extends javax.swing.JPanel {
    
    private MediaView viewer;
    private MediaPlayer player;
    private JFXPanel p;
    private Scene s;
    private Message listener;

    /**
     * Creates new form VideoPanel
     */
    public VideoPanel(URL media, Message listener, Rectangle size) {
        initComponents();
        this.listener = listener;
        p = new JFXPanel();
        this.add(p, java.awt.BorderLayout.CENTER);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(size);
                play(media);
            }
        });
        Platform.setImplicitExit(false);
    }
    
    private void play(URL file) {
        if (player != null && player.getStatus() != MediaPlayer.Status.STOPPED) {
            player.stop();
            player.dispose();
        }
        Media m = new Media(file.toString());
        player = new MediaPlayer(m);
        viewer.setMediaPlayer(player);
        player.play();
        System.out.println("Playing...");
    }
    
    private void initFX(Rectangle size) {
        
        StackPane pane = new StackPane();
        s = new Scene(pane, size.width, size.height, javafx.scene.paint.Color.BLACK);
        p.setScene(s);
        viewer = new MediaView();
        viewer.setPreserveRatio(true);
        pane.getChildren().add(viewer);
        pane.requestFocus();
        viewer.setFitHeight(size.height);
        viewer.setFitWidth(size.width);
    }

    public void stop(){
        if (player != null){
            player.stop();
            player.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClosed = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        btnClosed.setForeground(new java.awt.Color(153, 153, 153));
        btnClosed.setText("X");
        btnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedActionPerformed(evt);
            }
        });
        add(btnClosed, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void btnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedActionPerformed
       listener.status(Message.Type.CLOSEMEDIA,"#CLOSEMEDIA");
    }//GEN-LAST:event_btnClosedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosed;
    // End of variables declaration//GEN-END:variables
}
