/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webroom.gui;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.web.WebView;
import webroom.engine.Message;

/**
 *
 * @author patri
 */
public class WebPanel extends javax.swing.JPanel {
    
    private JFXPanel p;
    private Scene s;
    javafx.scene.web.WebView viewer;
    private Message listener;
    
    private BufferedImage texturedImage = null;

    /**
     * Creates new form VideoPanel
     */
    public WebPanel(URL media, Message listener, Rectangle size) {
        initComponents();
        this.listener = listener;
        p = new JFXPanel();
        txtLink.setText(media.toString());
        this.add(p, java.awt.BorderLayout.CENTER);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(size);
                play(media);
            }
        });
        Platform.setImplicitExit(false);
    }
    
    public void setImage(BufferedImage img) {
        texturedImage = img;
    }
    
    public WebPanel(String embeded, Message listener, Rectangle size) {
        initComponents();
        this.listener = listener;
        p = new JFXPanel();
        txtLink.setText("");
        txtLink.setVisible(false);
        jLabel1.setVisible(false);
        btnOpenInBrowser.setVisible(false);
        this.add(p, java.awt.BorderLayout.CENTER);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(size);
                embed(embeded);
            }
        });
        Platform.setImplicitExit(false);
    }
    
    private void play(URL file) {
        viewer.getEngine().load(file.toString());
    }
    
    @Override
    public void computeVisibleRect(Rectangle rec) {
        rec.height = 256;
        rec.width = 156;
        rec.x = 0;
        rec.y = 0;
    }

    @Override
    public void paint(Graphics g) {
        if (texturedImage != null) {
            super.paint(texturedImage.createGraphics());
        } else {
            super.paint(g);
        }
    }
    
    private void embed(String content) {
        //Support for Youtube
        if (content.startsWith("youtube=")) {
            content = content.replaceFirst("youtube=", "");
            content = "<iframe width=\"100%\" height=\"100%\" src='https://www.youtube.com/embed/" + content + "?autoplay=1' frameborder=\"0\" allowfullscreen></iframe>";
        } else if (content.startsWith("vidme=")){
            content = content.replaceFirst("vidme=","");
            content = "<iframe src=\"https://vid.me/e/"+content+"?stats=1&autoplay=1\" width=\"100%\" height=\"100%\" frameborder=\"0\" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling=\"no\"></iframe>";
        }
        String html = "<html><body>" + content + "</body></html>";
        System.out.println("Setting content: " + content);
        viewer.getEngine().loadContent(html);
    }
    
    private void initFX(Rectangle size) {
        StackPane pane = new StackPane();
        s = new Scene(pane, size.width, size.height, javafx.scene.paint.Color.BLACK);
        p.setScene(s);
        viewer = new WebView();
        pane.getChildren().add(viewer);
        pane.requestFocus();
    }
    
    public void stop() {
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                viewer.getEngine().loadContent("<html><body></body></html>");
                viewer = null;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panToolbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLink = new javax.swing.JTextField();
        btnOpenInBrowser = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Link");

        txtLink.setEditable(false);
        txtLink.setText("http://...");

        btnOpenInBrowser.setText("Open...");
        btnOpenInBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenInBrowserActionPerformed(evt);
            }
        });

        btnClose.setForeground(new java.awt.Color(153, 153, 153));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panToolbarLayout = new javax.swing.GroupLayout(panToolbar);
        panToolbar.setLayout(panToolbarLayout);
        panToolbarLayout.setHorizontalGroup(
            panToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLink, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenInBrowser)
                .addContainerGap())
        );
        panToolbarLayout.setVerticalGroup(
            panToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panToolbarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnOpenInBrowser)
                    .addComponent(btnClose)))
        );

        add(panToolbar, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void btnOpenInBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenInBrowserActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop d = Desktop.getDesktop();
                if (d != null) {
                    d.browse(new URI(viewer.getEngine().getDocument().getBaseURI()));
                }
            } catch (URISyntaxException ex) {
                Logger.getLogger(WebPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(WebPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenInBrowserActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        listener.onCloseView(this);        
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOpenInBrowser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panToolbar;
    private javax.swing.JTextField txtLink;
    // End of variables declaration//GEN-END:variables
}
